[features]
seeds = false
skip-lint = false
[programs.devnet]
r21_metaplex_tests = "7ghLrtu6EqZuRcNQX5cvWp8THJ6tgfbSXEAKZ8GhVRy4"
[programs.localnet]
r21_metaplex_tests = "7ghLrtu6EqZuRcNQX5cvWp8THJ6tgfbSXEAKZ8GhVRy4"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://solana-devnet.g.alchemy.com/v2/U71i04jmVQDCCrqqCD_WkO-PH_XWkrGT"
cluster = "localnet"
wallet = "/home/vscode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy_init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"